spring:
  application:
    name: VaultKeep
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  servlet:
    context-path: /api

vaultkeep:
  app:
    jwtSecret: ${JWT_SECRET:defaultSecretForDevOnly}
    jwtExpirationMs: 86400000