name: DevSecOps Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    env:
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
    steps:
      # 1. Check out the code
      - uses: actions/checkout@v4

      # 2. Set up Java 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # 3. Setup Gradle
      # This handles caching automatically and optimizes the Gradle daemon
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      # 4. Build the Application
      - name: Build with Gradle
        run: ./gradlew build

      # 5. Install Snyk CLI
      # Install the tool directly so it uses the Java 21 environment
      - name: Install Snyk CLI
        uses: snyk/actions/setup@master

      # 6. Run Snyk Security Scan
      # Uses the installed CLI to scan dependencies (SCA) using the Java 21 setup
      - name: Snyk Security Scan
        run: snyk test --all-projects --severity-threshold=high
        continue-on-error: false  # Fails the pipeline if High severity vulnerabilities are found (Security Gate)
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}